### ISSUE TITLE
Using miniskirt to test Rails engine models

### ISSUE THREAD

**Issue by partydrone** [stephencelis/minifacture#19]
In a new Rails 4 engine, given the model test:

```
## test/models/job_manager/job_test.rb
require 'test_helper'

module JobManager
  describe Job do
    before do
      @job = Factory.build(:job)
    end

    it "is a valid object" do
      @job.valid?.must_equal true
    end
  end
end
```

… and the factory definition:

```
## test/factories/job_manager/job.rb
module JobManager
  Factory.define :job do |j|
    j.title 'Job Title %d'
    j.description 'Lorem ipusum dolor sit amet consecateur ad piscin'
  end
end
```

The following error occurs:

```
uninitialized constant Job
Exception `NameError' at:
```

… which traces back to `@job = Factory.build(:job)` in the model test. It doesn't matter if I wrap the factory definition in the engine module or not.

What is the proper way to use miniskirt when testing Rails engine models?

**Comment by stephencelis** [comment]
`Factory.define` doesn't use the current scope to resolve constants, but you should be able to do the following:

``` ruby
Factory.define :job, class: JobManager::Job do
  # ...
end
```

**Comment by stephencelis** [comment]
Closing for now. Let me know if the above doesn't work.
