### ISSUE TITLE
About the naming

### ISSUE THREAD

**Issue by jsborjesson** [stephencelis/minifacture#20]
Hi!

First of all I want to thank you for contributing to open source, I tried this
and it's awesome - I love simple solutions like this.

There is one thing I feel uncomfortable with though, and that is the naming. I
understand what it has derived from and it _is_ clever, but I still think it's
a problem.

Naming like this enforces the view that programming is a "boy's club". I
want women to feel welcome in the open source community, and I think
"Miniskirt" can make people feel uncomfortable.

I think you should consider renaming the project. I understand that it is a
pain to do so, and that a mirror would have to stay up for a while, but I don't
believe that technical debt is a good enough reason to keep a potentially
offensive name, and I think that changing it would set a good example for the
Ruby community.

If you agree with this and come up with a new name, I'd be happy to make the
changes for you and send a pull request.

Thank you for your time and good work!

**Comment by stephencelis** [comment]
Totally agree and this very task has been on my backlog for awhile. This project has been dormant for a very long time, though, so it's easy to forget about. Let me see if I can come up with a more suitable name sometime this weekend.

**Comment by jsborjesson** [comment]
Glad to hear, thank you! :-)

**Comment by jsborjesson** [comment]
Wow that was quick, and the name is even more clever - I'm impressed!

**Comment by stephencelis** [comment]
You gave me the nudge I needed :) Thanks!

**Comment by jsborjesson** [comment]
Happy to do it, and really excited to use this!
