### ISSUE TITLE
Weird error with Ruby 1.9.x

### ISSUE THREAD

**Issue by ream88** [stephencelis/minifacture#5]
Although I'm using Ruby 1.9.3, bundler refuses to install the newest version 1.1:

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    miniskirt (= 1.1.0) ruby depends on
      activesupport (~> 2.2) ruby

    rails (= 3.1.1) ruby depends on
      activesupport (3.1.1)
```

Maybe following line in `.gemspec` is the problem?

``` ruby
s.add_dependency "activesupport",
    RUBY_VERSION >= "1.9" ? "~> 2.2" : "~> 3.0.0"
```

**Comment by ream88** [comment]
Sorry, maybe I'm confused, but should this line look something like:

``` ruby
s.add_dependency "activesupport",
    RUBY_VERSION >= "1.9" ? "~> 3.0" : "~> 2.2"
```

instead of

``` ruby
s.add_dependency "activesupport",
    RUBY_VERSION >= "1.9" ? "~> 2.2" : "~> 3.0"
```

**Comment by ream88** [comment]
Ok, I'm confused :)

Thanks for the super fast answer! Great gem!

**Comment by stephencelis** [comment]
ActiveSupport adds a few features to Ruby 1.8 that exist in 1.9 natively, but some of these weren't added to ActiveSupport until 3.0. Thus: if Ruby version >= 1.9, only require ActiveSupport 2.2 or greater, otherwise (i.e., if it's < Ruby 1.9), require 3.0 or greater.

**Comment by ream88** [comment]
Ahh, ok thank you for clarification!
